/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    BracketNode: typeof import('./src/components/rule-flow/nodes/BracketNode.vue')['default']
    CloseBracketNode: typeof import('./src/components/rule-flow/nodes/CloseBracketNode.vue')['default']
    ConditionNode: typeof import('./src/components/rule-flow/nodes/ConditionNode.vue')['default']
    ContextMenu: typeof import('./src/components/rule-flow/ContextMenu.vue')['default']
    DropzoneBackground: typeof import('./src/components/rule-flow/DropzoneBackground.vue')['default']
    FlowSidebar: typeof import('./src/components/rule-flow/FlowSidebar.vue')['default']
    IconCommunity: typeof import('./src/components/icons/IconCommunity.vue')['default']
    IconDocumentation: typeof import('./src/components/icons/IconDocumentation.vue')['default']
    IconEcosystem: typeof import('./src/components/icons/IconEcosystem.vue')['default']
    IconSupport: typeof import('./src/components/icons/IconSupport.vue')['default']
    IconTooling: typeof import('./src/components/icons/IconTooling.vue')['default']
    JoinEdge: typeof import('./src/components/rule-flow/edges/JoinEdge.vue')['default']
    OpenBracketNode: typeof import('./src/components/rule-flow/nodes/OpenBracketNode.vue')['default']
    ParametersReplacePattern: typeof import('./src/components/replace-pattern/ParametersReplacePattern.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    RuleBuilder: typeof import('./src/components/RuleBuilder.vue')['default']
    RuleFlowBuilder: typeof import('./src/components/rule-flow/RuleFlowBuilder.vue')['default']
    RuleList: typeof import('./src/components/rule-flow/RuleList.vue')['default']
    RulePreview: typeof import('./src/components/rule-flow/RulePreview.vue')['default']
    ShortcutsOverlay: typeof import('./src/components/rule-flow/ShortcutsOverlay.vue')['default']
    SimpleEdge: typeof import('./src/components/rule-flow/edges/SimpleEdge.vue')['default']
    StandardReplacePattern: typeof import('./src/components/replace-pattern/StandardReplacePattern.vue')['default']
  }
}
